CREATE TABLE "landing_page_config" (
	"id" text PRIMARY KEY DEFAULT 'default' NOT NULL,
	"seo_title" text DEFAULT 'Veracity - Plataforma de Pesquisas Eleitorais',
	"seo_description" text DEFAULT 'Sistema profissional para gestão de pesquisas eleitorais com GPS, gravação de áudio e detecção de fraudes em tempo real.',
	"seo_keywords" text DEFAULT 'pesquisa eleitoral, coleta de dados, GPS, anti-fraude, LGPD',
	"og_image" text,
	"hero_headline" text DEFAULT 'Pesquisas Eleitorais com Credibilidade Total',
	"hero_subheadline" text DEFAULT 'Sistema profissional de coleta de dados com GPS, gravação de áudio e detecção de fraudes em tempo real. Utilizado pelos principais institutos de pesquisa do Brasil.',
	"hero_cta" text DEFAULT 'Começar Agora',
	"hero_cta_secondary" text DEFAULT 'Ver Demonstração',
	"hero_image" text,
	"stats_enabled" boolean DEFAULT true,
	"stats" jsonb DEFAULT '[{"value":"+500K","label":"Entrevistas Realizadas"},{"value":"99.8%","label":"Precisão GPS"},{"value":"24/7","label":"Monitoramento"},{"value":"<1%","label":"Taxa de Fraude"}]'::jsonb,
	"features_title" text DEFAULT 'Por que escolher o Veracity?',
	"features_subtitle" text DEFAULT 'Tecnologia de ponta para pesquisas confiáveis',
	"features" jsonb DEFAULT '[]'::jsonb,
	"testimonials_title" text DEFAULT 'O que nossos clientes dizem',
	"testimonials" jsonb DEFAULT '[]'::jsonb,
	"testimonials_enabled" boolean DEFAULT true,
	"faq_title" text DEFAULT 'Perguntas Frequentes',
	"faqs" jsonb DEFAULT '[]'::jsonb,
	"faq_enabled" boolean DEFAULT true,
	"cta_title" text DEFAULT 'Pronto para revolucionar suas pesquisas?',
	"cta_subtitle" text DEFAULT 'Comece gratuitamente e descubra como o Veracity pode transformar sua operação de campo.',
	"cta_button" text DEFAULT 'Criar conta grátis',
	"primary_color" text,
	"secondary_color" text,
	"accent_color" text,
	"footer_text" text DEFAULT 'Desenvolvido no Brasil para institutos de pesquisa exigentes.',
	"footer_links" jsonb DEFAULT '[]'::jsonb,
	"google_analytics_id" text,
	"custom_head_scripts" text,
	"custom_body_scripts" text,
	"updated_at" timestamp DEFAULT now(),
	"updated_by" varchar
);
--> statement-breakpoint
ALTER TABLE "landing_page_config" ADD CONSTRAINT "landing_page_config_updated_by_users_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;